# Generated by Django 5.2.16 on 2026-07-26 14:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='شناسه یکتا (UUID)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان ایجاد رکورد')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='تاریخ و زمان آخرین بروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال یا غیرفعال بودن رکورد')),
                ('name', models.CharField(help_text='نام شرکت', max_length=255, unique=True)),
                ('website', models.URLField(blank=True, help_text='وب\u200cسایت شرکت', null=True)),
                ('description', models.TextField(blank=True, help_text='درباره شرکت', null=True)),
                ('logo', models.ImageField(blank=True, help_text='لوگوی شرکت', null=True, upload_to='company_logos/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='شناسه یکتا (UUID)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان ایجاد رکورد')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='تاریخ و زمان آخرین بروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال یا غیرفعال بودن رکورد')),
                ('email', models.EmailField(help_text='ایمیل کاربر به عنوان نام کاربری', max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, help_text='نام', max_length=150)),
                ('last_name', models.CharField(blank=True, help_text='نام خانوادگی', max_length=150)),
                ('role', models.CharField(choices=[('job_seeker', 'کارجو'), ('employer', 'کارفرما'), ('admin', 'مدیر سیستم')], default='job_seeker', help_text='نقش کاربر', max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, help_text='شرکت مرتبط (برای کارفرماها)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.company')),
                ('groups', models.ManyToManyField(blank=True, related_name='core_user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='core_user_permissions_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
