# Generated by Django 5.2.16 on 2026-07-26 17:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='شناسه یکتا (UUID)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان ایجاد رکورد')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='تاریخ و زمان آخرین بروزرسانی')),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال یا غیرفعال بودن رکورد')),
                ('phone', models.CharField(blank=True, help_text='شماره تماس کارجو', max_length=20, null=True)),
                ('resume', models.FileField(blank=True, help_text='فایل رزومه کارجو', null=True, upload_to='resumes/')),
                ('user', models.OneToOneField(help_text='حساب کاربری مرتبط با کارجو', on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to='core.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
