# Generated by Django 5.2.16 on 2026-08-17 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('reviewing', 'در حال بررسی'), ('shortlisted', 'لیست کوتاه'), ('accepted', 'تایید شده'), ('rejected', 'رد شده')], max_length=20, verbose_name='وضعیت جدید')),
                ('note', models.TextField(blank=True, null=True, verbose_name='يادداشت / توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان تغییر')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.application', verbose_name='درخواست استخدام')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes_made', to=settings.AUTH_USER_MODEL, verbose_name='تغییر داده شده توسط')),
            ],
            options={
                'verbose_name': 'تاریخچه درخواست',
                'verbose_name_plural': 'تاریخچه درخواست\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.candidate'),
        ),
    ]
