# Generated by Django 5.2.16 on 2026-08-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_enable_pgvector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار بررسی'), ('reviewing', 'در حال بررسی'), ('shortlisted', 'لیست کوتاه'), ('accepted', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20),
        ),
    ]
