# Generated by Django 5.2.16 on 2026-08-31 15:28

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='skills_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
